### ISSUE TITLE
DynoYarn WebUI doesn't update last health check status

### ISSUE THREAD

**Issue by boobpoop** [linkedin/dynoyarn#1]
Hi, I have a problem about starting DynoYarn Driver. I configured 15 nodemangers in Driver but I found the Last health-update was always the time that Node Manager resgistered in Resource Manager:

![image](https://user-images.githubusercontent.com/40508489/140644443-8e4c8d07-a98e-4d8f-b065-83ecf2c8c7a4.png)

I added some logs in nodemanager and I found  nodemanager hearbeat status was normal :

![image](https://user-images.githubusercontent.com/40508489/140644810-cfc6083f-fda2-4c76-aa7f-b79da90c77f6.png)

is there anything wrong about Last health-update? can anyone answer me ?

**Comment by oliverhu** [comment]
@hungj any idea?

**Comment by hungj** [comment]
Hi @boobpoop - the health update time does not update on every heartbeat.

Health update time is controlled by a couple factors:
1. Health check script. If you have one configured via `yarn.nodemanager.health-checker.script.path`, this will update every `yarn.nodemanager.health-checker.interval-ms` milliseconds (default 10 minutes).
2. Disk check. Controlled via `yarn.nodemanager.disk-health-checker.enable` (default true). If this is true this will update every `yarn.nodemanager.disk-health-checker.interval-ms` milliseconds (default 2 minutes).

Then the time in the UI should be updated every MAX(health-check-interval, disk-check-interval) milliseconds.

If both of these are not configured then I would not expect this time to be updated in the UI.

**Comment by boobpoop** [comment]
@hungj Thanks a lot . I configured true via `yarn.nodemanager.disk-health-checker.enable` in dynoyarn-site.xml and it worked. I misunderstood the concept of heartbeat and health check. I think the issue can be closed.
